//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Country", Namespace="http://schemas.datacontract.org/2004/07/HotelService.HotelClasses")]
    [System.SerializableAttribute()]
    public partial class Country : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CountryIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CountryId {
            get {
                return this.CountryIdField;
            }
            set {
                if ((this.CountryIdField.Equals(value) != true)) {
                    this.CountryIdField = value;
                    this.RaisePropertyChanged("CountryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CountryName {
            get {
                return this.CountryNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryNameField, value) != true)) {
                    this.CountryNameField = value;
                    this.RaisePropertyChanged("CountryName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="City", Namespace="http://schemas.datacontract.org/2004/07/HotelService.HotelClasses")]
    [System.SerializableAttribute()]
    public partial class City : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CityIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CountryIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CityId {
            get {
                return this.CityIdField;
            }
            set {
                if ((this.CityIdField.Equals(value) != true)) {
                    this.CityIdField = value;
                    this.RaisePropertyChanged("CityId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CityName {
            get {
                return this.CityNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CityNameField, value) != true)) {
                    this.CityNameField = value;
                    this.RaisePropertyChanged("CityName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CountryId {
            get {
                return this.CountryIdField;
            }
            set {
                if ((this.CountryIdField.Equals(value) != true)) {
                    this.CountryIdField = value;
                    this.RaisePropertyChanged("CountryId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RoomType", Namespace="http://schemas.datacontract.org/2004/07/HotelService.HotelClasses")]
    [System.SerializableAttribute()]
    public partial class RoomType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoomTypField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RId {
            get {
                return this.RIdField;
            }
            set {
                if ((this.RIdField.Equals(value) != true)) {
                    this.RIdField = value;
                    this.RaisePropertyChanged("RId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RoomTyp {
            get {
                return this.RoomTypField;
            }
            set {
                if ((object.ReferenceEquals(this.RoomTypField, value) != true)) {
                    this.RoomTypField = value;
                    this.RaisePropertyChanged("RoomTyp");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RoomDetails", Namespace="http://schemas.datacontract.org/2004/07/HotelService.HotelClasses")]
    [System.SerializableAttribute()]
    public partial class RoomDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HotelIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RateAdultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RateChildField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalRoomTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HotelId {
            get {
                return this.HotelIdField;
            }
            set {
                if ((object.ReferenceEquals(this.HotelIdField, value) != true)) {
                    this.HotelIdField = value;
                    this.RaisePropertyChanged("HotelId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RId {
            get {
                return this.RIdField;
            }
            set {
                if ((this.RIdField.Equals(value) != true)) {
                    this.RIdField = value;
                    this.RaisePropertyChanged("RId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RateAdult {
            get {
                return this.RateAdultField;
            }
            set {
                if ((this.RateAdultField.Equals(value) != true)) {
                    this.RateAdultField = value;
                    this.RaisePropertyChanged("RateAdult");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RateChild {
            get {
                return this.RateChildField;
            }
            set {
                if ((this.RateChildField.Equals(value) != true)) {
                    this.RateChildField = value;
                    this.RaisePropertyChanged("RateChild");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalRoomType {
            get {
                return this.TotalRoomTypeField;
            }
            set {
                if ((this.TotalRoomTypeField.Equals(value) != true)) {
                    this.TotalRoomTypeField = value;
                    this.RaisePropertyChanged("TotalRoomType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HotelDetails", Namespace="http://schemas.datacontract.org/2004/07/HotelService.HotelClasses")]
    [System.SerializableAttribute()]
    public partial class HotelDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AcRoomsAdultRateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AcRoomsChildtRateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ContactNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HotelAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HotelCityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HotelDesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HotelIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HotelNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NonAcRoomsAdultRateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NonAcRoomsChildtRateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalAcRoomsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalNonAcRoomsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalRoomsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AcRoomsAdultRate {
            get {
                return this.AcRoomsAdultRateField;
            }
            set {
                if ((this.AcRoomsAdultRateField.Equals(value) != true)) {
                    this.AcRoomsAdultRateField = value;
                    this.RaisePropertyChanged("AcRoomsAdultRate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AcRoomsChildtRate {
            get {
                return this.AcRoomsChildtRateField;
            }
            set {
                if ((this.AcRoomsChildtRateField.Equals(value) != true)) {
                    this.AcRoomsChildtRateField = value;
                    this.RaisePropertyChanged("AcRoomsChildtRate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ContactNo {
            get {
                return this.ContactNoField;
            }
            set {
                if ((this.ContactNoField.Equals(value) != true)) {
                    this.ContactNoField = value;
                    this.RaisePropertyChanged("ContactNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country {
            get {
                return this.CountryField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryField, value) != true)) {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HotelAddress {
            get {
                return this.HotelAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.HotelAddressField, value) != true)) {
                    this.HotelAddressField = value;
                    this.RaisePropertyChanged("HotelAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HotelCity {
            get {
                return this.HotelCityField;
            }
            set {
                if ((object.ReferenceEquals(this.HotelCityField, value) != true)) {
                    this.HotelCityField = value;
                    this.RaisePropertyChanged("HotelCity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HotelDes {
            get {
                return this.HotelDesField;
            }
            set {
                if ((object.ReferenceEquals(this.HotelDesField, value) != true)) {
                    this.HotelDesField = value;
                    this.RaisePropertyChanged("HotelDes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HotelId {
            get {
                return this.HotelIdField;
            }
            set {
                if ((object.ReferenceEquals(this.HotelIdField, value) != true)) {
                    this.HotelIdField = value;
                    this.RaisePropertyChanged("HotelId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HotelName {
            get {
                return this.HotelNameField;
            }
            set {
                if ((object.ReferenceEquals(this.HotelNameField, value) != true)) {
                    this.HotelNameField = value;
                    this.RaisePropertyChanged("HotelName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NonAcRoomsAdultRate {
            get {
                return this.NonAcRoomsAdultRateField;
            }
            set {
                if ((this.NonAcRoomsAdultRateField.Equals(value) != true)) {
                    this.NonAcRoomsAdultRateField = value;
                    this.RaisePropertyChanged("NonAcRoomsAdultRate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NonAcRoomsChildtRate {
            get {
                return this.NonAcRoomsChildtRateField;
            }
            set {
                if ((this.NonAcRoomsChildtRateField.Equals(value) != true)) {
                    this.NonAcRoomsChildtRateField = value;
                    this.RaisePropertyChanged("NonAcRoomsChildtRate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalAcRooms {
            get {
                return this.TotalAcRoomsField;
            }
            set {
                if ((this.TotalAcRoomsField.Equals(value) != true)) {
                    this.TotalAcRoomsField = value;
                    this.RaisePropertyChanged("TotalAcRooms");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalNonAcRooms {
            get {
                return this.TotalNonAcRoomsField;
            }
            set {
                if ((this.TotalNonAcRoomsField.Equals(value) != true)) {
                    this.TotalNonAcRoomsField = value;
                    this.RaisePropertyChanged("TotalNonAcRooms");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalRooms {
            get {
                return this.TotalRoomsField;
            }
            set {
                if ((this.TotalRoomsField.Equals(value) != true)) {
                    this.TotalRoomsField = value;
                    this.RaisePropertyChanged("TotalRooms");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertCountry", ReplyAction="http://tempuri.org/IService1/InsertCountryResponse")]
        string InsertCountry(Hotel.ServiceReference1.Country Incountry);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertCountry", ReplyAction="http://tempuri.org/IService1/InsertCountryResponse")]
        System.Threading.Tasks.Task<string> InsertCountryAsync(Hotel.ServiceReference1.Country Incountry);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertCity", ReplyAction="http://tempuri.org/IService1/InsertCityResponse")]
        string InsertCity(Hotel.ServiceReference1.City Incity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertCity", ReplyAction="http://tempuri.org/IService1/InsertCityResponse")]
        System.Threading.Tasks.Task<string> InsertCityAsync(Hotel.ServiceReference1.City Incity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Insertroomtype", ReplyAction="http://tempuri.org/IService1/InsertroomtypeResponse")]
        string Insertroomtype(Hotel.ServiceReference1.RoomType Inroomtype);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Insertroomtype", ReplyAction="http://tempuri.org/IService1/InsertroomtypeResponse")]
        System.Threading.Tasks.Task<string> InsertroomtypeAsync(Hotel.ServiceReference1.RoomType Inroomtype);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertRoomDetails", ReplyAction="http://tempuri.org/IService1/InsertRoomDetailsResponse")]
        string InsertRoomDetails(Hotel.ServiceReference1.RoomDetails Inroomdetails);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertRoomDetails", ReplyAction="http://tempuri.org/IService1/InsertRoomDetailsResponse")]
        System.Threading.Tasks.Task<string> InsertRoomDetailsAsync(Hotel.ServiceReference1.RoomDetails Inroomdetails);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Addhotel", ReplyAction="http://tempuri.org/IService1/AddhotelResponse")]
        string Addhotel(Hotel.ServiceReference1.HotelDetails AH);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Addhotel", ReplyAction="http://tempuri.org/IService1/AddhotelResponse")]
        System.Threading.Tasks.Task<string> AddhotelAsync(Hotel.ServiceReference1.HotelDetails AH);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Upadtehotel", ReplyAction="http://tempuri.org/IService1/UpadtehotelResponse")]
        string Upadtehotel(Hotel.ServiceReference1.HotelDetails UH);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Upadtehotel", ReplyAction="http://tempuri.org/IService1/UpadtehotelResponse")]
        System.Threading.Tasks.Task<string> UpadtehotelAsync(Hotel.ServiceReference1.HotelDetails UH);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getallhotel", ReplyAction="http://tempuri.org/IService1/getallhotelResponse")]
        Hotel.ServiceReference1.HotelDetails[] getallhotel();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getallhotel", ReplyAction="http://tempuri.org/IService1/getallhotelResponse")]
        System.Threading.Tasks.Task<Hotel.ServiceReference1.HotelDetails[]> getallhotelAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCountries", ReplyAction="http://tempuri.org/IService1/GetCountriesResponse")]
        string[] GetCountries();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCountries", ReplyAction="http://tempuri.org/IService1/GetCountriesResponse")]
        System.Threading.Tasks.Task<string[]> GetCountriesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCities", ReplyAction="http://tempuri.org/IService1/GetCitiesResponse")]
        string[] GetCities(string countname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCities", ReplyAction="http://tempuri.org/IService1/GetCitiesResponse")]
        System.Threading.Tasks.Task<string[]> GetCitiesAsync(string countname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetHoteIdies", ReplyAction="http://tempuri.org/IService1/GetHoteIdiesResponse")]
        string[] GetHoteIdies();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetHoteIdies", ReplyAction="http://tempuri.org/IService1/GetHoteIdiesResponse")]
        System.Threading.Tasks.Task<string[]> GetHoteIdiesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetHotelDetails", ReplyAction="http://tempuri.org/IService1/GetHotelDetailsResponse")]
        Hotel.ServiceReference1.HotelDetails GetHotelDetails(string Hid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetHotelDetails", ReplyAction="http://tempuri.org/IService1/GetHotelDetailsResponse")]
        System.Threading.Tasks.Task<Hotel.ServiceReference1.HotelDetails> GetHotelDetailsAsync(string Hid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Gethoteroomtype", ReplyAction="http://tempuri.org/IService1/GethoteroomtypeResponse")]
        string[] Gethoteroomtype();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Gethoteroomtype", ReplyAction="http://tempuri.org/IService1/GethoteroomtypeResponse")]
        System.Threading.Tasks.Task<string[]> GethoteroomtypeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Removehotel", ReplyAction="http://tempuri.org/IService1/RemovehotelResponse")]
        string Removehotel(string RH);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Removehotel", ReplyAction="http://tempuri.org/IService1/RemovehotelResponse")]
        System.Threading.Tasks.Task<string> RemovehotelAsync(string RH);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Hotel.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Hotel.ServiceReference1.IService1>, Hotel.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string InsertCountry(Hotel.ServiceReference1.Country Incountry) {
            return base.Channel.InsertCountry(Incountry);
        }
        
        public System.Threading.Tasks.Task<string> InsertCountryAsync(Hotel.ServiceReference1.Country Incountry) {
            return base.Channel.InsertCountryAsync(Incountry);
        }
        
        public string InsertCity(Hotel.ServiceReference1.City Incity) {
            return base.Channel.InsertCity(Incity);
        }
        
        public System.Threading.Tasks.Task<string> InsertCityAsync(Hotel.ServiceReference1.City Incity) {
            return base.Channel.InsertCityAsync(Incity);
        }
        
        public string Insertroomtype(Hotel.ServiceReference1.RoomType Inroomtype) {
            return base.Channel.Insertroomtype(Inroomtype);
        }
        
        public System.Threading.Tasks.Task<string> InsertroomtypeAsync(Hotel.ServiceReference1.RoomType Inroomtype) {
            return base.Channel.InsertroomtypeAsync(Inroomtype);
        }
        
        public string InsertRoomDetails(Hotel.ServiceReference1.RoomDetails Inroomdetails) {
            return base.Channel.InsertRoomDetails(Inroomdetails);
        }
        
        public System.Threading.Tasks.Task<string> InsertRoomDetailsAsync(Hotel.ServiceReference1.RoomDetails Inroomdetails) {
            return base.Channel.InsertRoomDetailsAsync(Inroomdetails);
        }
        
        public string Addhotel(Hotel.ServiceReference1.HotelDetails AH) {
            return base.Channel.Addhotel(AH);
        }
        
        public System.Threading.Tasks.Task<string> AddhotelAsync(Hotel.ServiceReference1.HotelDetails AH) {
            return base.Channel.AddhotelAsync(AH);
        }
        
        public string Upadtehotel(Hotel.ServiceReference1.HotelDetails UH) {
            return base.Channel.Upadtehotel(UH);
        }
        
        public System.Threading.Tasks.Task<string> UpadtehotelAsync(Hotel.ServiceReference1.HotelDetails UH) {
            return base.Channel.UpadtehotelAsync(UH);
        }
        
        public Hotel.ServiceReference1.HotelDetails[] getallhotel() {
            return base.Channel.getallhotel();
        }
        
        public System.Threading.Tasks.Task<Hotel.ServiceReference1.HotelDetails[]> getallhotelAsync() {
            return base.Channel.getallhotelAsync();
        }
        
        public string[] GetCountries() {
            return base.Channel.GetCountries();
        }
        
        public System.Threading.Tasks.Task<string[]> GetCountriesAsync() {
            return base.Channel.GetCountriesAsync();
        }
        
        public string[] GetCities(string countname) {
            return base.Channel.GetCities(countname);
        }
        
        public System.Threading.Tasks.Task<string[]> GetCitiesAsync(string countname) {
            return base.Channel.GetCitiesAsync(countname);
        }
        
        public string[] GetHoteIdies() {
            return base.Channel.GetHoteIdies();
        }
        
        public System.Threading.Tasks.Task<string[]> GetHoteIdiesAsync() {
            return base.Channel.GetHoteIdiesAsync();
        }
        
        public Hotel.ServiceReference1.HotelDetails GetHotelDetails(string Hid) {
            return base.Channel.GetHotelDetails(Hid);
        }
        
        public System.Threading.Tasks.Task<Hotel.ServiceReference1.HotelDetails> GetHotelDetailsAsync(string Hid) {
            return base.Channel.GetHotelDetailsAsync(Hid);
        }
        
        public string[] Gethoteroomtype() {
            return base.Channel.Gethoteroomtype();
        }
        
        public System.Threading.Tasks.Task<string[]> GethoteroomtypeAsync() {
            return base.Channel.GethoteroomtypeAsync();
        }
        
        public string Removehotel(string RH) {
            return base.Channel.Removehotel(RH);
        }
        
        public System.Threading.Tasks.Task<string> RemovehotelAsync(string RH) {
            return base.Channel.RemovehotelAsync(RH);
        }
    }
}
